# Generated by Django 5.2 on 2025-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
