# Generated by Django 5.2 on 2025-04-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0002_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
